### ISSUE TITLE
Not accepting str as user

### ISSUE THREAD

**Issue by ampledata** [ampledata/aprs#22]
```
>>> a = aprs.TCP('W2GMD', 'xxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gba/.pyenv/versions/undef.net-3.6.2/lib/python3.6/site-packages/aprs-7.0.0rc3-py3.6.egg/aprs/classes.py", line 273, in __init__
    aprs_filter = aprs_filter or b'/'.join([b'p', user])  # Unicode
TypeError: sequence item 1: expected a bytes-like object, str found
```

**Comment by askpatrickw** [comment]
I hit this as well on python 3.6.5.
You wrote this, so I'm sure you know, but for others if you're following along the README use this:

    CALL = b"YOURCALL"
    APRS_IS = b"Your_APRSIS_Code"
    a = aprs.TC(CALL, APRS_IS)
    a.start()
    a.receive(callback=p)
