### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Frame' and 'bytes'

### ISSUE THREAD

**Issue by ampledata** [ampledata/aprs#23]
```
2017-10-11 11:35:26,856 aprs INFO aprs.classes.start:304 - Connect To 129.15.108.112:14580
2017-10-11 11:35:27,022 aprs INFO aprs.classes.start:311 - Connect Result "b'# aprsc 2.1.4-g408ed49'"
2017-10-11 11:35:27,024 aprs INFO aprs.classes.start:315 - Auth To 129.15.108.112:14580
2017-10-11 11:35:27,099 aprs INFO aprs.classes.start:323 - Auth Result "b'# logresp W2GMD verified, server FOURTH'"
W2GMD>APRS:>Hello World!
2017-10-11 11:35:27,100 aprs INFO aprs.classes.send:340 - Sending frame="W2GMD>APRS:>Hello World!"
Traceback (most recent call last):
  File "aprscmd.py", line 10, in <module>
    a.send(frame)
  File "/Users/gba/p/undef.net/aprs/aprs/classes.py", line 343, in send
    _frame = bytes(frame + b'\n\r')
TypeError: unsupported operand type(s) for +: 'Frame' and 'bytes'
```

**Comment by budude2** [comment]
I submitted a fix

#24
