### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by m1geo** [ampledata/aprs#27]
Hello. I was trying to install this, but receive the following error

> C:\Logs>pip install aprs
> Collecting aprs
>   Using cached https://files.pythonhosted.org/packages/2b/0f/1b1975d9a265ba647b3efccf87a1ec0350cc3dabbaecd667f7831ed9f23e/aprs-7.0.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\geosma01\AppData\Local\Temp\pip-install-6pniz52z\aprs\setup.py", line 46, in <module>
>         long_description=open('README.rst').read(),
>       File "c:\program files (x86)\python-32\lib\encodings\cp1252.py", line 23, in decode
>         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>     UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4443: character maps to <undefined>
> 
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\geosma01\AppData\Local\Temp\pip-install-6pniz52z\aprs\

I also tried from inside a Python environment with import pip, pip.main(["install","aprs"]) and got the same error.

M1GEO

**Comment by idlecore** [comment]
Fixed by #33
